"""
Class to help with key entry less typos
"""

class MTKeys:
    """class to enumerate keys used in module"""

    data = "data"
    date = "date"


    # TVMaze
    tvmaze = "tvmaze"
    summary = "summary"
    name = "name"
    url = "url"
    image = "image"
    medium = "medium"
    original = "original"
    idOfMedia = "id"
    image = "image"
    medium = "medium"
    original = "original"
    show = "show"
    premiered = "premiered"
    genres = "genres"
    season = "season"
    number = "number"
    airdate = "airdate"
    endDate = "endDate"
    premiereDate = "premiereDate"
    network = "network"
    urlGetShows = "urlGetShows"
    status = "status"

    moviedb = "moviedb"
    omdb = "omdb"
    tvdb = "tvdb"
    tvdbToken = "tvdbToken"
    search = "search"
    getinfo = "getinfo"
    imdbID = "imdbID"
    imdb_id = "imdb_id"
    idOfMedia = "id"
    id = "id"
    year = "year"

    Year = "Year"
    Released = "Released"
    Title = "Title"
    Plot = "Plot"
    Director = "Director"


    mediaType = "type"
    attrib = "attrib"
    datatype = "datatype"
    Movie = "Movie"
    TV = "TV"
    total_results = "total_results"
    results = "results"

    seasons = "seasons"
    totalSeasons = "totalSeasons"
    totalSpecials = "totalSpecials"
    totalEpisodes = "totalEpisodes"

    COMMENT = "COMMENT"
    DATE_RELEASED = "DATE_RELEASED"
    DIRECTOR = "DIRECTOR"
    Name = "Name"
    PART_NUMBER = "PART_NUMBER"
    Simple = "Simple"
    String = "String"
    Tag = "Tag"
    Tags = "Tags"
    Targets = "Targets"
    TargetTypeValue = "TargetTypeValue"
    TITLE = "TITLE"
    TOTAL_PARTS = "TOTAL_PARTS"

    creditsOfVideo = "credits"
    crew = "crew"
    department = "department"
    Directing = "Directing"
    Director = "Director"
    job = "job"
    release_date = "release_date"
    title = "title"

    airedSeason = "airedSeason"
    absoluteNumber = "absoluteNumber"
    airedEpisodeNumber = "airedEpisodeNumber"
    airedSeason = "airedSeason"
    airedSeasonID = "airedSeasonID"
    airsAfterSeason = "airsAfterSeason"
    airsBeforeEpisode = "airsBeforeEpisode"
    airsBeforeSeason = "airsBeforeSeason"
    director = "director"
    directors = "directors"
    dvdChapter = "dvdChapter"
    dvdDiscid = "dvdDiscid"
    dvdEpisodeNumber = "dvdEpisodeNumber"
    dvdSeason = "dvdSeason"
    episodeName = "episodeName"
    filename = "filename"
    firstAired = "firstAired"
    genre = "genre"
    guestStars = "guestStars"
    idOfMedia = "id"
    imdbId = "imdbId"
    language = "language"
    lastUpdated = "lastUpdated"
    lastUpdatedBy = "lastUpdatedBy"
    overview = "overview"
    productionCode = "productionCode"
    seriesId = "seriesId"
    seriesName = "seriesName"
    showUrl = "showUrl"
    siteRating = "siteRating"
    siteRatingCount = "siteRatingCount"
    thumbAdded = "thumbAdded"
    thumbAuthor = "thumbAuthor"
    thumbHeight = "thumbHeight"
    thumbWidth = "thumbWidth"
    writers = "writers"
